# Numpy

In [1]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


## Multi-dimensional arrays in Numpy

In [2]:
import numpy as np

arr0 = np.array(23)
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [11, 12, 13]]])
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


0
1
2
3


## Printing Multi-dimensional arrays:

In [9]:
print("----------------------------------------")
print("1D array:")
print(arr1)
print("----------------------------------------")
print("2D array:")
print(arr2)
print("----------------------------------------")
print("3D array:")
print(arr3)
print("----------------------------------------")

----------------------------------------
1D array:
[1 2 3 4]
----------------------------------------
2D array:
[[1 2 3 4]
 [5 6 7 8]]
----------------------------------------
3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
----------------------------------------


## Printing specific elements from multi-dimensional arrays:
- Note: you can also use negative indexing like you do in 1D arrays.

In [10]:
print(arr1[1])
print(arr2[1][1])
print(arr3[1][1][1])

2
6
12


## Printing the shape of multi-dimensional arrays:
- shape describes number of entries in every dimension.

In [11]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(4,)
(2, 4)
(2, 2, 3)


## Copying arrays

In [13]:
arrcpy = np.copy(arr3)
print(arrcpy)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]


## Concatenate arrays
- use np.concatenate() to concatenate numpy arrays
- It is important to specify in which dimension we are going to perform the concatenation. 
- This is done through axis parameter.
- pass all arrays as tuple elements in first parameter
- Specify the axis of concatenation in second parameter
- axis = dimension


In [17]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arrconcat = np.concatenate((arr1, arr2), axis = 0)

## Sorting numpy arrays:
- use np.sort() to return a sorted list

In [21]:
arr3 = np.array([423,523,5,534,23,234,235,245,5,234])
arrsorted = np.sort(arr3)
print(arrsorted)

[  5   5  23 234 234 235 245 423 523 534]


## Task: Extract RGB values from an image and convert it into array

In [ ]:
Ass